export const initialHeroes = [
   {
      name: "Abaddon",
      image: "abaddon.jpg",
      id: 1,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_outworld_003.jpg",
   },
   {
      name: "Underlord",
      image: "abyssal_underlord.jpg",
      id: 2,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_outworld_002.jpg",
   },
   {
      name: "Alchemist",
      image: "alchemist.jpg",
      id: 3,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_001.jpg",
   },
   {
      name: "Ancient Apparition",
      image: "ancient_apparition.jpg",
      id: 4,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_ice_001.jpg",
   },
   {
      name: "Antimage",
      image: "antimage.jpg",
      id: 5,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_outworld_001.jpg",
   },
   {
      name: "Arc Warden",
      image: "arc_warden.jpg",
      id: 6,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_outworld_004.jpg",
   },
   {
      name: "Axe",
      image: "axe.jpg",
      id: 7,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_001.jpg",
   },
   {
      name: "Bane",
      image: "bane.jpg",
      id: 8,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_outworld_003.jpg",
   },
   {
      name: "Batrider",
      image: "batrider.jpg",
      id: 9,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_forest_004.jpg",
   },
   {
      name: "Beastmaster",
      image: "beastmaster.jpg",
      id: 10,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_rocky_004.jpg",
   },
   {
      name: "Bloodseeker",
      image: "bloodseeker.jpg",
      id: 11,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_fire_001.jpg",
   },
   {
      name: "Bounty Hunter",
      image: "bounty_hunter.jpg",
      id: 12,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_jungle_001.jpg",
   },
   {
      name: "Brewmaster",
      image: "brewmaster.jpg",
      id: 13,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_forest_001.jpg",
   },
   {
      name: "Bristleback",
      image: "bristleback.jpg",
      id: 14,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_forest_004.jpg",
   },
   {
      name: "Broodmother",
      image: "broodmother.jpg",
      id: 15,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_forest_003.jpg",
   },
   {
      name: "Centaur Warrunner",
      image: "centaur.jpg",
      id: 16,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_004.jpg",
   },
   {
      name: "Chaos Knight",
      image: "chaos_knight.jpg",
      id: 17,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_003.jpg",
   },
   {
      name: "Chen",
      image: "chen.jpg",
      id: 18,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_rocky_002.jpg",
   },
   {
      name: "Clinkz",
      image: "clinkz.jpg",
      id: 19,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_fire_004.jpg",
   },
   {
      name: "Crystal Maiden",
      image: "crystal_maiden.jpg",
      id: 20,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_ice_003.jpg",
   },
   {
      name: "Dark Seer",
      image: "dark_seer.jpg",
      id: 21,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_outworld_004.jpg",
   },
   {
      name: "Dark Willow",
      image: "dark_willow.jpg",
      id: 22,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_field_002.jpg",
   },
   {
      name: "Dawnbreaker",
      image: "dawnbreaker.jpg",
      id: 23,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_field_002.jpg",
   },
   {
      name: "Dazzle",
      image: "dazzle.jpg",
      id: 24,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_outworld_002.jpg",
   },
   {
      name: "Death Prophet",
      image: "death_prophet.jpg",
      id: 25,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_outworld_001.jpg",
   },
   {
      name: "Disruptor",
      image: "disruptor.jpg",
      id: 26,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_field_003.jpg",
   },
   {
      name: "Doom",
      image: "doom_bringer.jpg",
      id: 27,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_fire_003.jpg",
   },
   {
      name: "Dragon Knight",
      image: "dragon_knight.jpg",
      id: 28,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_002.jpg",
   },
   {
      name: "Drow Ranger",
      image: "drow_ranger.jpg",
      id: 29,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_ice_002.jpg",
   },
   {
      name: "Earth Spirit",
      image: "earth_spirit.jpg",
      id: 30,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_forest_002.jpg",
   },
   {
      name: "Earthshaker",
      image: "earthshaker.jpg",
      id: 31,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_forest_001.jpg",
   },
   {
      name: "Elder Titan",
      image: "elder_titan.jpg",
      id: 32,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_004.jpg",
   },
   {
      name: "Ember Spirit",
      image: "ember_spirit.jpg",
      id: 33,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_fire_002.jpg",
   },
   {
      name: "Enchantress",
      image: "enchantress.jpg",
      id: 34,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_field_001.jpg",
   },
   {
      name: "Enigma",
      image: "enigma.jpg",
      id: 35,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_outworld_004.jpg",
   },
   {
      name: "Faceless Void",
      image: "faceless_void.jpg",
      id: 36,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_outworld_003.jpg",
   },
   {
      name: "Nature's Prophet",
      image: "furion.jpg",
      id: 37,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_forest_004.jpg",
   },
   {
      name: "Grimstroke",
      image: "grimstroke.jpg",
      id: 38,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_outworld_003.jpg",
   },
   {
      name: "Gyrocopter",
      image: "gyrocopter.jpg",
      id: 39,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_sky_004.jpg",
   },
   {
      name: "Hoodwink",
      image: "hoodwink.jpg",
      id: 40,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_field_004.jpg",
   },
   {
      name: "Huskar",
      image: "huskar.jpg",
      id: 41,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_001.jpg",
   },
   {
      name: "Invoker",
      image: "invoker.jpg",
      id: 42,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_sky_004.jpg",
   },
   {
      name: "Jakiro",
      image: "jakiro.jpg",
      id: 43,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_ice_004.jpg",
   },
   {
      name: "Juggernaut",
      image: "juggernaut.jpg",
      id: 44,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_sky_003.jpg",
   },
   {
      name: "Keeper of the light",
      image: "keeper_of_the_light.jpg",
      id: 45,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_field_002.jpg",
   },
   {
      name: "Kez",
      image: "kez.jpg",
      id: 126,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_sky_002.jpg",
   },
   {
      name: "Kunkka",
      image: "kunkka.jpg",
      id: 46,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_water_004.jpg",
   },
   {
      name: "Legion Commander",
      image: "legion_commander.jpg",
      id: 47,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_003.jpg",
   },
   {
      name: "Leshrac",
      image: "leshrac.jpg",
      id: 48,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_ice_001.jpg",
   },
   {
      name: "Lich",
      image: "lich.jpg",
      id: 49,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_ice_002.jpg",
   },
   {
      name: "Lifestealer",
      image: "life_stealer.jpg",
      id: 50,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_004.jpg",
   },
   {
      name: "Lina",
      image: "lina.jpg",
      id: 51,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_fire_001.jpg",
   },
   {
      name: "Lion",
      image: "lion.jpg",
      id: 52,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_forest_003.jpg",
   },
   {
      name: "Lone Druid",
      image: "lone_druid.jpg",
      id: 53,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_jungle_003.jpg",
   },
   {
      name: "Luna",
      image: "luna.jpg",
      id: 54,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_ice_003.jpg",
   },
   {
      name: "Lycan",
      image: "lycan.jpg",
      id: 55,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_forest_003.jpg",
   },
   {
      name: "Magnus",
      image: "magnataur.jpg",
      id: 56,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_forest_002.jpg",
   },
   {
      name: "Marci",
      image: "marci.jpg",
      id: 57,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_field_003.jpg",
   },
   {
      name: "Mars",
      image: "mars.jpg",
      id: 58,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_002.jpg",
   },
   {
      name: "Medusa",
      image: "medusa.jpg",
      id: 59,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_jungle_004.jpg",
   },
   {
      name: "Meepo",
      image: "meepo.jpg",
      id: 60,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_field_001.jpg",
   },
   {
      name: "Mirana",
      image: "mirana.jpg",
      id: 61,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_ice_004.jpg",
   },
   {
      name: "Monkey King",
      image: "monkey_king.jpg",
      id: 62,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_jungle_002.jpg",
   },
   {
      name: "Morphling",
      image: "morphling.jpg",
      id: 63,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_water_003.jpg",
   },
   {
      name: "Muerta",
      image: "muerta.jpg",
      id: 64,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_outworld_001.jpg",
   },
   {
      name: "Naga Siren",
      image: "naga_siren.jpg",
      id: 65,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_water_001.jpg",
   },
   {
      name: "Necrophos",
      image: "necrolyte.jpg",
      id: 66,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_outworld_002.jpg",
   },
   {
      name: "Shadow Fiend",
      image: "nevermore.jpg",
      id: 67,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_fire_004.jpg",
   },
   {
      name: "Night Stalker",
      image: "night_stalker.jpg",
      id: 68,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_outworld_002.jpg",
   },
   {
      name: "Nyx",
      image: "nyx_assassin.jpg",
      id: 69,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_sky_003.jpg",
   },
   {
      name: "Outworld Destroyer",
      image: "obsidian_destroyer.jpg",
      id: 70,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_outworld_001.jpg",
   },
   {
      name: "Ogre Magi",
      image: "ogre_magi.jpg",
      id: 71,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_forest_002.jpg",
   },
   {
      name: "Omniknight",
      image: "omniknight.jpg",
      id: 72,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_field_001.jpg",
   },
   {
      name: "Oracle",
      image: "oracle.jpg",
      id: 73,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_sky_002.jpg",
   },
   {
      name: "Pangolier",
      image: "pangolier.jpg",
      id: 74,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_forest_001.jpg",
   },
   {
      name: "Phantom Assassin",
      image: "phantom_assassin.jpg",
      id: 75,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_outworld_002.jpg",
   },
   {
      name: "Phantom Lancer",
      image: "phantom_lancer.jpg",
      id: 76,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_jungle_001.jpg",
   },
   {
      name: "Phoenix",
      image: "phoenix.jpg",
      id: 77,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_sky_003.jpg",
   },
   {
      name: "Primal Beast",
      image: "primal_beast.jpg",
      id: 78,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_003.jpg",
   },
   {
      name: "Puck",
      image: "puck.jpg",
      id: 79,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_outworld_001.jpg",
   },
   {
      name: "Pudge",
      image: "pudge.jpg",
      id: 80,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_jungle_004.jpg",
   },
   {
      name: "Pugna",
      image: "pugna.jpg",
      id: 81,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_outworld_004.jpg",
   },
   {
      name: "Queen of pain",
      image: "queenofpain.jpg",
      id: 82,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_fire_003.jpg",
   },
   {
      name: "Clockwerk",
      image: "rattletrap.jpg",
      id: 83,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_field_004.jpg",
   },
   {
      name: "Razor",
      image: "razor.jpg",
      id: 84,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_sky_002.jpg",
   },
   {
      name: "Riki",
      image: "riki.jpg",
      id: 85,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_outworld_004.jpg",
   },
   {
      name: "Ringmaster",
      image: "ringmaster.jpg",
      id: 125,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_field_003.jpg",
   },
   {
      name: "Rubick",
      image: "rubick.jpg",
      id: 86,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_outworld_003.jpg",
   },
   {
      name: "Sand King",
      image: "sand_king.jpg",
      id: 87,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_rocky_003.jpg",
   },
   {
      name: "Shadow Demon",
      image: "shadow_demon.jpg",
      id: 88,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_fire_002.jpg",
   },
   {
      name: "Shadow Shaman",
      image: "shadow_shaman.jpg",
      id: 89,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_rocky_002.jpg",
   },
   {
      name: "Timbersaw",
      image: "shredder.jpg",
      id: 90,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_field_002.jpg",
   },
   {
      name: "Silencer",
      image: "silencer.jpg",
      id: 91,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_sky_001.jpg",
   },
   {
      name: "Wraith king",
      image: "skeleton_king.jpg",
      id: 92,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_outworld_002.jpg",
   },
   {
      name: "Skywrath Mage",
      image: "skywrath_mage.jpg",
      id: 93,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_sky_001.jpg",
   },
   {
      name: "Slardar",
      image: "slardar.jpg",
      id: 94,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_water_001.jpg",
   },
   {
      name: "Slark",
      image: "slark.jpg",
      id: 95,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_water_001.jpg",
   },
   {
      name: "Snapfire",
      image: "snapfire.jpg",
      id: 96,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_field_003.jpg",
   },
   {
      name: "Sniper",
      image: "sniper.jpg",
      id: 97,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_field_001.jpg",
   },
   {
      name: "Spectre",
      image: "spectre.jpg",
      id: 98,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_outworld_001.jpg",
   },
   {
      name: "Spirit Breaker",
      image: "spirit_breaker.jpg",
      id: 99,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_001.jpg",
   },
   {
      name: "Storm Spirit",
      image: "storm_spirit.jpg",
      id: 100,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_sky_002.jpg",
   },
   {
      name: "Sven",
      image: "sven.jpg",
      id: 101,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_ice_001.jpg",
   },
   {
      name: "Techies",
      image: "techies.jpg",
      id: 102,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_field_001.jpg",
   },
   {
      name: "Templar Assassin",
      image: "templar_assassin.jpg",
      id: 103,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_outworld_004.jpg",
   },
   {
      name: "Terrorblade",
      image: "terrorblade.jpg",
      id: 104,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_outworld_003.jpg",
   },
   {
      name: "Tidehunter",
      image: "tidehunter.jpg",
      id: 105,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_water_002.jpg",
   },
   {
      name: "Tinker",
      image: "tinker.jpg",
      id: 106,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_field_003.jpg",
   },
   {
      name: "Tiny",
      image: "tiny.jpg",
      id: 107,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_forest_004.jpg",
   },
   {
      name: "Treant Protector",
      image: "treant.jpg",
      id: 108,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_forest_003.jpg",
   },
   {
      name: "Troll Warlord",
      image: "troll_warlord.jpg",
      id: 109,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_forest_002.jpg",
   },
   {
      name: "Tusk",
      image: "tusk.jpg",
      id: 110,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_ice_002.jpg",
   },
   {
      name: "Undying",
      image: "undying.jpg",
      id: 111,
      attribute: "strength",
      selected: true,
      loadout: "loadout_bg_rocky_001.jpg",
   },
   {
      name: "Ursa",
      image: "ursa.jpg",
      id: 112,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_forest_001.jpg",
   },
   {
      name: "Vengeful Spirit",
      image: "vengefulspirit.jpg",
      id: 113,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_sky_001.jpg",
   },
   {
      name: "Venomancer",
      image: "venomancer.jpg",
      id: 114,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_jungle_003.jpg",
   },
   {
      name: "Viper",
      image: "viper.jpg",
      id: 115,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_jungle_001.jpg",
   },
   {
      name: "Visage",
      image: "visage.jpg",
      id: 116,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_ice_003.jpg",
   },
   {
      name: "Void Spirit",
      image: "void_spirit.jpg",
      id: 117,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_outworld_002.jpg",
   },
   {
      name: "Warlock",
      image: "warlock.jpg",
      id: 118,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_fire_001.jpg",
   },
   {
      name: "Weaver",
      image: "weaver.jpg",
      id: 119,
      attribute: "agility",
      selected: true,
      loadout: "loadout_bg_jungle_002.jpg",
   },
   {
      name: "Windranger",
      image: "windrunner.jpg",
      id: 120,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_field_004.jpg",
   },
   {
      name: "Winter Wyvern",
      image: "winter_wyvern.jpg",
      id: 121,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_ice_004.jpg",
   },
   {
      name: "IO",
      image: "wisp.jpg",
      id: 122,
      attribute: "universal",
      selected: true,
      loadout: "loadout_bg_sky_004.jpg",
   },
   {
      name: "Witch Doctor",
      image: "witch_doctor.jpg",
      id: 123,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_jungle_001.jpg",
   },
   {
      name: "Zeus",
      image: "zuus.jpg",
      id: 124,
      attribute: "intelligence",
      selected: true,
      loadout: "loadout_bg_outworld_001.jpg",
   },
];
